BookstoreMVC/Models/ErrorViewModel.cs
namespace BoookstoreMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookstoreMVC/Models/ShoppingCartViewModel.cs
using DataAccess.Entities;
using System;
using System.Collections.Generic;
using System.Linq;

namespace BookstoreMVC.Models
{
    public class ShoppingCartViewModel
    {
        public List<Product> Products { get; set; }

        public decimal GetTotalPrice()
        {
            return Products.Sum(p => p.Price);
        }
    }
}

BookstoreMVC/Controllers/CheckoutController.cs
using BookstoreMVC.Models;
using BookstoreMVC.Constants;
using BookstoreMVC.Extensions;
using BusinessLogic.Services.ProductService;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System.Collections.Generic;
using DataAccess.Entities;

namespace BookstoreMVC.Controllers
{
    public class CheckoutController : Controller
    {

        private readonly IHttpContextAccessor _httpContextAccessor;
        private ISession _session => _httpContextAccessor.HttpContext.Session;

        IProductService _productService;
        ShoppingCartViewModel _shoppingCart;

        public CheckoutController(IProductService productService, IHttpContextAccessor httpContextAccessor)
        {
            _productService = productService;

            _httpContextAccessor = httpContextAccessor;
        }

        [HttpGet]
        public async Task<IActionResult> AddToCart(int productId)
        {
            var product = await _productService.GetProductById(productId);

            _shoppingCart = GetShoppingCart();
            if (_shoppingCart == null)
            {
                _shoppingCart = new ShoppingCartViewModel()
                {
                    Products = new List<Product>()
                };
            }

            _shoppingCart.Products.Add(product);
            UpdateShoppingCart(_shoppingCart);

            return RedirectToAction("List", "Product");
        }

        [HttpGet]
        public async Task<IActionResult> Cart()
        {
            _shoppingCart = GetShoppingCart();

            return View(_shoppingCart);
        }

        [HttpPost]
        public async Task<IActionResult> Cart(ShoppingCartViewModel shoppingCartView)
        {

            return View(_shoppingCart);
        }


        public void UpdateShoppingCart(ShoppingCartViewModel shoppingCart)
        {
            _session.SetComplexObject(SessionVariableNames.ShopingCart, shoppingCart);
        }

        public ShoppingCartViewModel GetShoppingCart()
        {
            return _session.GetComplexObject<ShoppingCartViewModel>(SessionVariableNames.ShopingCart);
        }
    }
}

BookstoreMVC/Controllers/HomeController.cs
using BoookstoreMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace BoookstoreMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookstoreMVC/Controllers/ProductController.cs
using BusinessLogic.Services.ProductService;
using DataAccess.Entities;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BoookstoreMvc.Controllers
{
    public class ProductController : Controller
    {
        IProductService _productService;

        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var products = await _productService.GetAllProducts();

            return View(products);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(Product product)
        {
            await _productService.AddProduct(product);

            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int productId)
        {
            await _productService.RemoveProduct(productId);

            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int productId)
        {
            var product = await _productService.GetProductById(productId);

            return View(product);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Product product)
        {
            await _productService.UpdateProduct(product);

            return RedirectToAction("List");
        }
    }
}

BookstoreMVC/Controllers/UserController.cs
namespace BoookstoreMvc.Controllers
{
    public class UserController
    {
    }
}

BookstoreMVC/Views/Checkout/Cart.cshtml
@model BookstoreMVC.Models.ShoppingCartViewModel

@{
    ViewData["Title"] = "Cart";
}

<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductTypeId" class="control-label"></label>
                <input asp-for="ProductTypeId" class="form-control" />
                <span asp-validation-for="ProductTypeId" class="text-danger"></span>
            </div>*@

            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Your cart</span>
                        <span class="badge bg-primary rounded-pill">@Model.Products.Count</span>
                    </h4>
                    <ul class="list-group mb-3">
                        @foreach (var item in Model.Products)
                        {
                            <li class="list-group-item d-flex justify-content-between lh-sm">
                                <div>
                                    <h6 class="my-0">@item.Name</h6>
                                    <small class="text-muted">@item.Name desc</small>
                                </div>
                                <span class="text-muted">@item.Price zł</span>
                            </li>
                        }

                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (PLN)</span>
                            <strong>@Model.GetTotalPrice()</strong>
                        </li>
                    </ul>

                </div>
                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Billing address</h4>
                    <div class="row g-3">
                        <div class="col-sm-6">
                            <label for="firstName" class="form-label">First name</label>
                            <input type="text" class="form-control" id="firstName" placeholder="" value="" required="">
                            <div class="invalid-feedback">
                                Valid first name is required.
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <label for="lastName" class="form-label">Last name</label>
                            <input type="text" class="form-control" id="lastName" placeholder="" value="" required="">
                            <div class="invalid-feedback">
                                Valid last name is required.
                            </div>
                        </div>

                        <div class="col-12">
                            <label for="username" class="form-label">Username</label>
                            <div class="input-group has-validation">
                                @*<span class="input-group-text">Username</span>*@
                                <input type="text" class="form-control" id="username" placeholder="Username" required="">
                                <div class="invalid-feedback">
                                    Your username is required.
                                </div>
                            </div>
                        </div>

                        <div class="col-12">
                            <label for="email" class="form-label">Email <span class="text-muted">(Optional)</span></label>
                            <input type="email" class="form-control" id="email" placeholder="you@example.com">
                            <div class="invalid-feedback">
                                Please enter a valid email address for shipping updates.
                            </div>
                        </div>

                        <div class="col-12">
                            <label for="address" class="form-label">Address</label>
                            <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="">
                            <div class="invalid-feedback">
                                Please enter your shipping address.
                            </div>
                        </div>

                        <div class="col-12">
                            <label for="address2" class="form-label">Address 2 <span class="text-muted">(Optional)</span></label>
                            <input type="text" class="form-control" id="address2" placeholder="Apartment or suite">
                        </div>

                        <div class="col-md-5">
                            <label for="country" class="form-label">Country</label>
                            <select class="form-select" id="country" required="">
                                <option value="">Choose...</option>
                                <option>United States</option>
                            </select>
                            <div class="invalid-feedback">
                                Please select a valid country.
                            </div>
                        </div>

                        <div class="col-md-4">
                            <label for="state" class="form-label">State</label>
                            <select class="form-select" id="state" required="">
                                <option value="">Choose...</option>
                                <option>California</option>
                            </select>
                            <div class="invalid-feedback">
                                Please provide a valid state.
                            </div>
                        </div>

                        <div class="col-md-3">
                            <label for="zip" class="form-label">Zip</label>
                            <input type="text" class="form-control" id="zip" placeholder="" required="">
                            <div class="invalid-feedback">
                                Zip code required.
                            </div>
                        </div>
                    </div>

                    <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
                </div>
            </div>
        </form>
    </div>
</div>

BookstoreMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BookstoreMVC/Views/Product/Create.cshtml
@model DataAccess.Entities.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductTypeId" class="control-label"></label>
                <input asp-for="ProductTypeId" class="form-control" />
                <span asp-validation-for="ProductTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookstoreMVC/Views/Product/Edit.cshtml
@model DataAccess.Entities.Product

@{
    ViewData["Title"] = "View";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductTypeId" class="control-label"></label>
                <input asp-for="ProductTypeId" class="form-control" />
                <span asp-validation-for="ProductTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookstoreMVC/Views/Product/List.cshtml
@model IEnumerable<DataAccess.Entities.Product>

@{
    ViewData["Title"] = "ProductsList";
}

<h1>ProductsList</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-lg-3">
            <div class="card shadow-sm">
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>

                <div class="card-body">
                    <p class="card-text">@Html.DisplayFor(modelItem => item.Name)</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="text-dark" asp-area="" asp-controller="Checkout" asp-action="AddToCart" asp-route-productId="@item.Id">Add to cart</a>
                            <a class="text-dark" asp-area="" asp-controller="Product" asp-action="Edit" asp-route-productId="@item.Id">Edit</a>
                            <a class="text-dark" asp-area="" asp-controller="Product" asp-action="Delete" asp-route-productId="@item.Id">Delete</a>
                        </div>
                        <small class="text-muted">@Html.DisplayFor(modelItem => item.Price) zł</small>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

BookstoreMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using BookstoreMVC.Constants
@using BookstoreMVC.Models
@using BookstoreMVC.Extensions
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{

    var shoppingcart = HttpContextAccessor.HttpContext.Session.GetComplexObject<ShoppingCartViewModel>(SessionVariableNames.ShopingCart);

    var cartCount = shoppingcart != null ? shoppingcart.Products.Count : 0;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>
    <link rel="stylesheet" href="~/css/site.css?2" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookstore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="List">products</a>
                        </li>
                    </ul>
                    <div class="cart">
                        @if (cartCount > 0)
                        {
                            <a asp-area="" asp-controller="Checkout" asp-action="Cart">
                                <i class="fa cart-icon">&#xf07a;</i>
                                <span class='badge badge-warning' id='lblCartCount'> @cartCount </span>
                            </a>
                        }
                        else
                        {
                            <i class="fa cart-icon">&#xf07a;</i>
                        }
                    </div>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Bookstore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookstoreMVC/Views/Shared/_SidebarWidePartial.cshtml
<div class="flex-shrink-0 p-3 bg-white" style="width: 280px;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
        <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
        <span class="fs-5 fw-semibold">Collapsible</span>
    </a>
    <ul class="list-unstyled ps-0">
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
                Home
            </button>
            <div class="collapse show" id="home-collapse">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="#" class="link-dark rounded">Overview</a></li>
                    <li><a href="#" class="link-dark rounded">Updates</a></li>
                    <li><a href="#" class="link-dark rounded">Reports</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
                Dashboard
            </button>
            <div class="collapse" id="dashboard-collapse">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="#" class="link-dark rounded">Overview</a></li>
                    <li><a href="#" class="link-dark rounded">Weekly</a></li>
                    <li><a href="#" class="link-dark rounded">Monthly</a></li>
                    <li><a href="#" class="link-dark rounded">Annually</a></li>
                </ul>
            </div>
        </li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
                Orders
            </button>
            <div class="collapse" id="orders-collapse">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="#" class="link-dark rounded">New</a></li>
                    <li><a href="#" class="link-dark rounded">Processed</a></li>
                    <li><a href="#" class="link-dark rounded">Shipped</a></li>
                    <li><a href="#" class="link-dark rounded">Returned</a></li>
                </ul>
            </div>
        </li>
        <li class="border-top my-3"></li>
        <li class="mb-1">
            <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
                Account
            </button>
            <div class="collapse" id="account-collapse">
                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                    <li><a href="#" class="link-dark rounded">New...</a></li>
                    <li><a href="#" class="link-dark rounded">Profile</a></li>
                    <li><a href="#" class="link-dark rounded">Settings</a></li>
                    <li><a href="#" class="link-dark rounded">Sign out</a></li>
                </ul>
            </div>
        </li>
    </ul>
</div>